version: "3.9"

networks:
  monitor-net:
    driver: bridge

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: arosage
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitor-net

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back-container
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - monitor-net

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - monitor-net

  # mobileApp:
  #   build:
  #     context: ./mobileApp
  #     dockerfile: Dockerfile
  #   container_name: mobile-app-container
  #   ports:
  #     - "19000:19000"
  #     - "19001:19001"
  #     - "19002:19002"
  #   volumes:
  #     - ./mobileApp:/app
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend
  #   networks:
  #     - monitor-net

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
