version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back-container
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: arosage
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mobileApp:
    build:
      context: ./mobileApp
      dockerfile: Dockerfile
    container_name: mobile-app-container
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./mobileApp:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data:
