name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      # Build and push frontend image
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./webapp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      # Build and push mobile image
      - name: Build and push Mobile image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mobileApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mobile:latest
